export const DELETE_COMMENT = 'DELETE_COMMENT';
export const ADD_COMMENT = 'ADD_COMMENT';
export const UPDATE_COMMENT = 'UPDATE_COMMENT';
export const GET_POST_COMMENTS = 'GET_POST_COMMENTS';
export const DELETE_POST_COMMENTS = 'DELETE_POST_COMMENTS';
